package vaadin.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Slider;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CentralDashboardView extends CssLayout {
	protected Button butUserManagement;
	protected Button butDeviceManagement;
	protected Button butLogout;
	protected Slider slider;
	protected ComboBox<java.lang.String> comboBox;
	protected Accordion accordion;
	protected Image image;
	protected Label label3;
	protected Label label2;
	protected Label label1;
	protected Label label;

	public CentralDashboardView() {
		Design.read(this);
	}
}
