package vaadin.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserDeviceControlView extends HorizontalLayout {
	protected Label label;
	protected CssLayout menu;
	protected Button advancedSetups;
	protected Button connectingDevices;
	protected Button allDevices;
	protected Button user;
	protected Button logOut;
	protected CssLayout csslayout;
	protected CssLayout contain1;
	protected VerticalLayout contain11;
	protected Label mainMessage;
	protected Label subMessage;
	protected CssLayout contain2;
	protected VerticalLayout contain21;
	protected CssLayout contain3;
	protected VerticalLayout contain31;
	protected CssLayout contain4;
	protected VerticalLayout contain41;
	protected CssLayout contain5;
	protected VerticalLayout contain51;
	protected CssLayout contain6;
	protected VerticalLayout contain61;
	protected CssLayout contain7;
	protected VerticalLayout contain71;
	protected CssLayout contain8;
	protected VerticalLayout contain81;
	protected CssLayout contain9;
	protected VerticalLayout contain91;
	protected CssLayout contain10;
	protected VerticalLayout contain101;

	public UserDeviceControlView() {
		Design.read(this);
	}
}
