package vaadin.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserDeviceControlView extends HorizontalLayout {
	protected Label label;
	protected CssLayout menu;
	protected Button setupDevice;
	protected Button activeDevices;
	protected Button allDevices;
	protected Button user;
	protected Button logOut;
	protected VerticalLayout vertical;
	protected GridLayout contain1;
	protected Label mainMessage;
	protected Label subMessage;
	protected GridLayout contain2;
	protected GridLayout contain3;
	protected GridLayout contain4;
	protected GridLayout contain5;
	protected GridLayout contain6;

	public UserDeviceControlView() {
		Design.read(this);
	}
}
