package vaadin.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserManagementView extends VerticalLayout {
	protected Button button1;
	protected Button button;
	protected Label label1;
	protected TextField textField;
	protected Button button2;
	protected Label label2;
	protected Label label3;
	protected TextArea textArea;
	protected ComboBox<java.lang.String> comboBox;
	protected Button button3;
	protected Button button4;
	protected Grid<?> grid;

	public UserManagementView() {
		Design.read(this);
	}
}
