
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package math.util;

import java.util.logging.Logger;

import gen.math.util.CalcInterface;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-01-04T15:44:45.404+08:00
 * Generated source version: 3.1.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "CalcService",
                      portName = "CalcPort",
                      targetNamespace = "http://util.math.gen/",
                      wsdlLocation = "file:/C:/Users/ThangLe/development/sts-bundle_test/workspace/CXFservicesMaven/src/main/webapp/wsdl/calcinterface.wsdl",
                      endpointInterface = "gen.math.util.CalcInterface")
                      
public class CalcPortImpl implements CalcInterface {

    private static final Logger LOG = Logger.getLogger(CalcPortImpl.class.getName());

    /* (non-Javadoc)
     * @see main.java.gen.math.util.CalcInterface#add(int arg0, int arg1)*
     */
    public int add(int arg0, int arg1) { 
        LOG.info("Executing operation add");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = arg0 + arg1;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see main.java.gen.math.util.CalcInterface#multiply(int arg0, int arg1)*
     */
    public int multiply(int arg0, int arg1) { 
        LOG.info("Executing operation multiply");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = arg0*arg1;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
