
package math.util.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-04T16:17:42.434+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class Calc_CalcPort_Client {

    private static final QName SERVICE_NAME = new QName("http://util.math/", "CalcService");

    private Calc_CalcPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalcService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CalcService ss = new CalcService(wsdlURL, SERVICE_NAME);
        Calc port = ss.getCalcPort();  
        
        {
        System.out.println("Invoking add...");
        int _add_arg0 = 1;
        int _add_arg1 = 2;
        int _add__return = port.add(_add_arg0, _add_arg1);
        System.out.println("add.result=" + _add__return);


        }
        {
        System.out.println("Invoking multiply...");
        int _multiply_arg0 = 3;
        int _multiply_arg1 = 4;
        int _multiply__return = port.multiply(_multiply_arg0, _multiply_arg1);
        System.out.println("multiply.result=" + _multiply__return);


        }

        System.exit(0);
    }

}
