package math.util.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-04T16:17:42.497+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://util.math/", name = "Calc")
@XmlSeeAlso({ObjectFactory.class})
public interface Calc {

    @WebMethod(action = "urn:Add")
    @RequestWrapper(localName = "add", targetNamespace = "http://util.math/", className = "math.util.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://util.math/", className = "math.util.client.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod(action = "urn:Multiply")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://util.math/", className = "math.util.client.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://util.math/", className = "math.util.client.MultiplyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
